name: crevify
description: A food delivery app for campus students
homepage: https://github.com/Sconl
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_central_dependency:
    git:
      url: git@github.com:Sconl/flutter_central_dependency.git
  timeline_tile: ^2.0.0
  confetti: ^0.7.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.10
  
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/_profile_placeholders/
