name: crevify
description: A food delivery app for campus students
author: Sconl Peter | Ace Cyber Space
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_central_dependency:
    git:
      url: git@github.com:Sconl/flutter-central-dependency.git
  shape_clipper:
    path: ./shape_clipper
  vector_math: ^2.1.4
            
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
