// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZACB_lxdI_XuxZIu7tL7m9L20c21TVFs',
    appId: '1:477837912041:web:4dbf8b7255d15bdb59cd78',
    messagingSenderId: '477837912041',
    projectId: 'crevify-83b45',
    authDomain: 'crevify-83b45.firebaseapp.com',
    storageBucket: 'crevify-83b45.appspot.com',
    measurementId: 'G-WQ95VVD9Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAiWq8x9mVxQZtbicBUHXkmQeF5qEMCkM',
    appId: '1:477837912041:android:552b772f009e157259cd78',
    messagingSenderId: '477837912041',
    projectId: 'crevify-83b45',
    storageBucket: 'crevify-83b45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4JP9OY0Kwig2TJ97IYJFoEny_jVHF8cU',
    appId: '1:477837912041:ios:3f1ca4ba02c70f1059cd78',
    messagingSenderId: '477837912041',
    projectId: 'crevify-83b45',
    storageBucket: 'crevify-83b45.appspot.com',
    iosBundleId: 'com.example.crevify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4JP9OY0Kwig2TJ97IYJFoEny_jVHF8cU',
    appId: '1:477837912041:ios:9eefa8da0c07b5cc59cd78',
    messagingSenderId: '477837912041',
    projectId: 'crevify-83b45',
    storageBucket: 'crevify-83b45.appspot.com',
    iosBundleId: 'com.example.crevify.RunnerTests',
  );
}
