// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5yePliFgNPks9caQ1lDYn_E71djhUgIE',
    appId: '1:331797684652:web:1bf6673a0d70b3389c5a09',
    messagingSenderId: '331797684652',
    projectId: 'crevify-app',
    authDomain: 'crevify-app.firebaseapp.com',
    storageBucket: 'crevify-app.appspot.com',
    measurementId: 'G-TFS3ZKDZZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeglp_WpL-RY5KJwFyPQ9OF5wJSuScId4',
    appId: '1:331797684652:android:cba21b82d512550b9c5a09',
    messagingSenderId: '331797684652',
    projectId: 'crevify-app',
    storageBucket: 'crevify-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2RY0M3k1V0tuGDPARIIT0OAYtoCKxTB0',
    appId: '1:331797684652:ios:d4236926c90a4f2d9c5a09',
    messagingSenderId: '331797684652',
    projectId: 'crevify-app',
    storageBucket: 'crevify-app.appspot.com',
    iosBundleId: 'com.example.crevify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2RY0M3k1V0tuGDPARIIT0OAYtoCKxTB0',
    appId: '1:331797684652:ios:6bf5b495def4b5739c5a09',
    messagingSenderId: '331797684652',
    projectId: 'crevify-app',
    storageBucket: 'crevify-app.appspot.com',
    iosBundleId: 'com.example.crevify.RunnerTests',
  );
}
